## Copyright (c) 2011 The WebM project authors. All Rights Reserved.
## 
## Use of this source code is governed by a BSD-style license
## that can be found in the LICENSE file in the root of the source
## tree. An additional intellectual property rights grant can be found
## in the file PATENTS.  All contributing project authors may
## be found in the AUTHORS file in the root of the source tree.
# This file automatically generated by configure. Do not edit!
TOOLCHAIN := generic-gnu
ALL_TARGETS += libs

PREFIX=/Users/devmarcos/Documents/GitHubRepos/CreationVideoPlayer/VLCKit-2.2.2/MobileVLCKit/ImportedSources/vlc/contrib/arm-apple-darwin11-armv7s
ifeq ($(MAKECMDGOALS),dist)
DIST_DIR?=vpx-vp8dx-vp9dx-nopost-nodocs-generic-gnu-v1.3.0
else
DIST_DIR?=$(DESTDIR)/Users/devmarcos/Documents/GitHubRepos/CreationVideoPlayer/VLCKit-2.2.2/MobileVLCKit/ImportedSources/vlc/contrib/arm-apple-darwin11-armv7s
endif
LIBSUBDIR=lib

VERSION_STRING=v1.3.0

VERSION_MAJOR=1
VERSION_MINOR=3
VERSION_PATCH=0

CONFIGURE_ARGS=--target=generic-gnu --enable-runtime-cpu-detect --disable-docs --disable-examples --disable-unit-tests --disable-install-bins --disable-install-docs --disable-vp8-encoder --disable-vp9-encoder --enable-pic --sdk-path=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.4.sdk --enable-vp8-decoder --disable-vp8-encoder --disable-vp9-encoder --prefix=/Users/devmarcos/Documents/GitHubRepos/CreationVideoPlayer/VLCKit-2.2.2/MobileVLCKit/ImportedSources/vlc/contrib/arm-apple-darwin11-armv7s
CONFIGURE_ARGS?=--target=generic-gnu --enable-runtime-cpu-detect --disable-docs --disable-examples --disable-unit-tests --disable-install-bins --disable-install-docs --disable-vp8-encoder --disable-vp9-encoder --enable-pic --sdk-path=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.4.sdk --enable-vp8-decoder --disable-vp8-encoder --disable-vp9-encoder --prefix=/Users/devmarcos/Documents/GitHubRepos/CreationVideoPlayer/VLCKit-2.2.2/MobileVLCKit/ImportedSources/vlc/contrib/arm-apple-darwin11-armv7s
