// This file is autogenerated by AggregateStaticPlugins.sh\n\n
int vlc_entry__a52 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_mms (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_output_file (int (*)(void *, void *, int, ...), void *);
int vlc_entry__adjust (int (*)(void *, void *, int, ...), void *);
int vlc_entry__adpcm (int (*)(void *, void *, int, ...), void *);
int vlc_entry__aes3 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__afile (int (*)(void *, void *, int, ...), void *);
int vlc_entry__aiff (int (*)(void *, void *, int, ...), void *);
int vlc_entry__amem (int (*)(void *, void *, int, ...), void *);
int vlc_entry__araw (int (*)(void *, void *, int, ...), void *);
int vlc_entry__asf (int (*)(void *, void *, int, ...), void *);
int vlc_entry__attachment (int (*)(void *, void *, int, ...), void *);
int vlc_entry__au (int (*)(void *, void *, int, ...), void *);
int vlc_entry__audio_format (int (*)(void *, void *, int, ...), void *);
int vlc_entry__audiounit_ios (int (*)(void *, void *, int, ...), void *);
int vlc_entry__avcodec (int (*)(void *, void *, int, ...), void *);
int vlc_entry__avformat (int (*)(void *, void *, int, ...), void *);
int vlc_entry__avi (int (*)(void *, void *, int, ...), void *);
int vlc_entry__avio (int (*)(void *, void *, int, ...), void *);
int vlc_entry__blend (int (*)(void *, void *, int, ...), void *);
int vlc_entry__caf (int (*)(void *, void *, int, ...), void *);
int vlc_entry__canvas (int (*)(void *, void *, int, ...), void *);
int vlc_entry__cc (int (*)(void *, void *, int, ...), void *);
int vlc_entry__cdg (int (*)(void *, void *, int, ...), void *);
int vlc_entry__chain (int (*)(void *, void *, int, ...), void *);
int vlc_entry__chorus_flanger (int (*)(void *, void *, int, ...), void *);
int vlc_entry__compressor (int (*)(void *, void *, int, ...), void *);
int vlc_entry__croppadd (int (*)(void *, void *, int, ...), void *);
int vlc_entry__cvdsub (int (*)(void *, void *, int, ...), void *);
int vlc_entry__dash (int (*)(void *, void *, int, ...), void *);
int vlc_entry__decomp (int (*)(void *, void *, int, ...), void *);
int vlc_entry__deinterlace (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_cdg (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_stl (int (*)(void *, void *, int, ...), void *);
int vlc_entry__diracsys (int (*)(void *, void *, int, ...), void *);
int vlc_entry__dolby_surround_decoder (int (*)(void *, void *, int, ...), void *);
int vlc_entry__dts (int (*)(void *, void *, int, ...), void *);
int vlc_entry__dvbsub (int (*)(void *, void *, int, ...), void *);
int vlc_entry__equalizer (int (*)(void *, void *, int, ...), void *);
int vlc_entry__es (int (*)(void *, void *, int, ...), void *);
int vlc_entry__filesystem (int (*)(void *, void *, int, ...), void *);
int vlc_entry__flac (int (*)(void *, void *, int, ...), void *);
int vlc_entry__flacsys (int (*)(void *, void *, int, ...), void *);
int vlc_entry__float_mixer (int (*)(void *, void *, int, ...), void *);
int vlc_entry__folder (int (*)(void *, void *, int, ...), void *);
int vlc_entry__freetype (int (*)(void *, void *, int, ...), void *);
int vlc_entry__freeze (int (*)(void *, void *, int, ...), void *);
int vlc_entry__ftp (int (*)(void *, void *, int, ...), void *);
int vlc_entry__g711 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__gain (int (*)(void *, void *, int, ...), void *);
int vlc_entry__grey_yuv (int (*)(void *, void *, int, ...), void *);
int vlc_entry__h264 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__hevc (int (*)(void *, void *, int, ...), void *);
int vlc_entry__http (int (*)(void *, void *, int, ...), void *);
int vlc_entry__httplive (int (*)(void *, void *, int, ...), void *);
int vlc_entry__i420_rgb (int (*)(void *, void *, int, ...), void *);
int vlc_entry__i420_yuy2 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__i422_i420 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__i422_yuy2 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__image (int (*)(void *, void *, int, ...), void *);
int vlc_entry__imem (int (*)(void *, void *, int, ...), void *);
int vlc_entry__integer_mixer (int (*)(void *, void *, int, ...), void *);
int vlc_entry__ios_dialog_provider (int (*)(void *, void *, int, ...), void *);
int vlc_entry__karaoke (int (*)(void *, void *, int, ...), void *);
int vlc_entry__libass (int (*)(void *, void *, int, ...), void *);
int vlc_entry__live555 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__logo (int (*)(void *, void *, int, ...), void *);
int vlc_entry__lpcm (int (*)(void *, void *, int, ...), void *);
int vlc_entry__mjpeg (int (*)(void *, void *, int, ...), void *);
int vlc_entry__mkv (int (*)(void *, void *, int, ...), void *);
int vlc_entry__mod (int (*)(void *, void *, int, ...), void *);
int vlc_entry__mono (int (*)(void *, void *, int, ...), void *);
int vlc_entry__mp4 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__mpeg_audio (int (*)(void *, void *, int, ...), void *);
int vlc_entry__mpgv (int (*)(void *, void *, int, ...), void *);
int vlc_entry__normvol (int (*)(void *, void *, int, ...), void *);
int vlc_entry__nsc (int (*)(void *, void *, int, ...), void *);
int vlc_entry__nsv (int (*)(void *, void *, int, ...), void *);
int vlc_entry__nuv (int (*)(void *, void *, int, ...), void *);
int vlc_entry__ogg (int (*)(void *, void *, int, ...), void *);
int vlc_entry__opus (int (*)(void *, void *, int, ...), void *);
int vlc_entry__packetizer_avparser (int (*)(void *, void *, int, ...), void *);
int vlc_entry__packetizer_copy (int (*)(void *, void *, int, ...), void *);
int vlc_entry__packetizer_dirac (int (*)(void *, void *, int, ...), void *);
int vlc_entry__packetizer_flac (int (*)(void *, void *, int, ...), void *);
int vlc_entry__packetizer_h264 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__packetizer_hevc (int (*)(void *, void *, int, ...), void *);
int vlc_entry__packetizer_mlp (int (*)(void *, void *, int, ...), void *);
int vlc_entry__packetizer_mpeg4audio (int (*)(void *, void *, int, ...), void *);
int vlc_entry__packetizer_mpeg4video (int (*)(void *, void *, int, ...), void *);
int vlc_entry__packetizer_mpegvideo (int (*)(void *, void *, int, ...), void *);
int vlc_entry__packetizer_vc1 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__param_eq (int (*)(void *, void *, int, ...), void *);
int vlc_entry__playlist (int (*)(void *, void *, int, ...), void *);
int vlc_entry__png (int (*)(void *, void *, int, ...), void *);
int vlc_entry__ps (int (*)(void *, void *, int, ...), void *);
int vlc_entry__pva (int (*)(void *, void *, int, ...), void *);
int vlc_entry__quartztext (int (*)(void *, void *, int, ...), void *);
int vlc_entry__rar (int (*)(void *, void *, int, ...), void *);
int vlc_entry__rawaud (int (*)(void *, void *, int, ...), void *);
int vlc_entry__rawdv (int (*)(void *, void *, int, ...), void *);
int vlc_entry__rawvid (int (*)(void *, void *, int, ...), void *);
int vlc_entry__rawvideo (int (*)(void *, void *, int, ...), void *);
int vlc_entry__record (int (*)(void *, void *, int, ...), void *);
int vlc_entry__rotate (int (*)(void *, void *, int, ...), void *);
int vlc_entry__rtp (int (*)(void *, void *, int, ...), void *);
int vlc_entry__rv32 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__sap (int (*)(void *, void *, int, ...), void *);
int vlc_entry__scale (int (*)(void *, void *, int, ...), void *);
int vlc_entry__scaletempo (int (*)(void *, void *, int, ...), void *);
int vlc_entry__scte27 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__sdp (int (*)(void *, void *, int, ...), void *);
int vlc_entry__securetransport (int (*)(void *, void *, int, ...), void *);
int vlc_entry__sftp (int (*)(void *, void *, int, ...), void *);
int vlc_entry__simple_channel_mixer (int (*)(void *, void *, int, ...), void *);
int vlc_entry__smooth (int (*)(void *, void *, int, ...), void *);
int vlc_entry__spatializer (int (*)(void *, void *, int, ...), void *);
int vlc_entry__speex (int (*)(void *, void *, int, ...), void *);
int vlc_entry__spudec (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stereo_widen (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stl (int (*)(void *, void *, int, ...), void *);
int vlc_entry__subsdec (int (*)(void *, void *, int, ...), void *);
int vlc_entry__subsdelay (int (*)(void *, void *, int, ...), void *);
int vlc_entry__substx3g (int (*)(void *, void *, int, ...), void *);
int vlc_entry__subsusf (int (*)(void *, void *, int, ...), void *);
int vlc_entry__subtitle (int (*)(void *, void *, int, ...), void *);
int vlc_entry__svcdsub (int (*)(void *, void *, int, ...), void *);
int vlc_entry__swscale (int (*)(void *, void *, int, ...), void *);
int vlc_entry__taglib (int (*)(void *, void *, int, ...), void *);
int vlc_entry__tcp (int (*)(void *, void *, int, ...), void *);
int vlc_entry__telx (int (*)(void *, void *, int, ...), void *);
int vlc_entry__theora (int (*)(void *, void *, int, ...), void *);
int vlc_entry__timecode (int (*)(void *, void *, int, ...), void *);
int vlc_entry__transform (int (*)(void *, void *, int, ...), void *);
int vlc_entry__trivial_channel_mixer (int (*)(void *, void *, int, ...), void *);
int vlc_entry__ts (int (*)(void *, void *, int, ...), void *);
int vlc_entry__tta (int (*)(void *, void *, int, ...), void *);
int vlc_entry__ty (int (*)(void *, void *, int, ...), void *);
int vlc_entry__udp (int (*)(void *, void *, int, ...), void *);
int vlc_entry__ugly_resampler (int (*)(void *, void *, int, ...), void *);
int vlc_entry__uleaddvaudio (int (*)(void *, void *, int, ...), void *);
int vlc_entry__vc1 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__vdr (int (*)(void *, void *, int, ...), void *);
int vlc_entry__vmem (int (*)(void *, void *, int, ...), void *);
int vlc_entry__vobsub (int (*)(void *, void *, int, ...), void *);
int vlc_entry__voc (int (*)(void *, void *, int, ...), void *);
int vlc_entry__vod_rtsp (int (*)(void *, void *, int, ...), void *);
int vlc_entry__vorbis (int (*)(void *, void *, int, ...), void *);
int vlc_entry__vout_ios2 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__vpx (int (*)(void *, void *, int, ...), void *);
int vlc_entry__wav (int (*)(void *, void *, int, ...), void *);
int vlc_entry__xa (int (*)(void *, void *, int, ...), void *);
int vlc_entry__xml (int (*)(void *, void *, int, ...), void *);
int vlc_entry__yuv (int (*)(void *, void *, int, ...), void *);
int vlc_entry__yuvp (int (*)(void *, void *, int, ...), void *);
int vlc_entry__yuy2_i420 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__yuy2_i422 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__zip (int (*)(void *, void *, int, ...), void *);
int vlc_entry__zvbi (int (*)(void *, void *, int, ...), void *);

const void *vlc_static_modules[] = {
 vlc_entry__a52,
 vlc_entry__access_mms,
 vlc_entry__access_output_file,
 vlc_entry__adjust,
 vlc_entry__adpcm,
 vlc_entry__aes3,
 vlc_entry__afile,
 vlc_entry__aiff,
 vlc_entry__amem,
 vlc_entry__araw,
 vlc_entry__asf,
 vlc_entry__attachment,
 vlc_entry__au,
 vlc_entry__audio_format,
 vlc_entry__audiounit_ios,
 vlc_entry__avcodec,
 vlc_entry__avformat,
 vlc_entry__avi,
 vlc_entry__avio,
 vlc_entry__blend,
 vlc_entry__caf,
 vlc_entry__canvas,
 vlc_entry__cc,
 vlc_entry__cdg,
 vlc_entry__chain,
 vlc_entry__chorus_flanger,
 vlc_entry__compressor,
 vlc_entry__croppadd,
 vlc_entry__cvdsub,
 vlc_entry__dash,
 vlc_entry__decomp,
 vlc_entry__deinterlace,
 vlc_entry__demux_cdg,
 vlc_entry__demux_stl,
 vlc_entry__diracsys,
 vlc_entry__dolby_surround_decoder,
 vlc_entry__dts,
 vlc_entry__dvbsub,
 vlc_entry__equalizer,
 vlc_entry__es,
 vlc_entry__filesystem,
 vlc_entry__flac,
 vlc_entry__flacsys,
 vlc_entry__float_mixer,
 vlc_entry__folder,
 vlc_entry__freetype,
 vlc_entry__freeze,
 vlc_entry__ftp,
 vlc_entry__g711,
 vlc_entry__gain,
 vlc_entry__grey_yuv,
 vlc_entry__h264,
 vlc_entry__hevc,
 vlc_entry__http,
 vlc_entry__httplive,
 vlc_entry__i420_rgb,
 vlc_entry__i420_yuy2,
 vlc_entry__i422_i420,
 vlc_entry__i422_yuy2,
 vlc_entry__image,
 vlc_entry__imem,
 vlc_entry__integer_mixer,
 vlc_entry__ios_dialog_provider,
 vlc_entry__karaoke,
 vlc_entry__libass,
 vlc_entry__live555,
 vlc_entry__logo,
 vlc_entry__lpcm,
 vlc_entry__mjpeg,
 vlc_entry__mkv,
 vlc_entry__mod,
 vlc_entry__mono,
 vlc_entry__mp4,
 vlc_entry__mpeg_audio,
 vlc_entry__mpgv,
 vlc_entry__normvol,
 vlc_entry__nsc,
 vlc_entry__nsv,
 vlc_entry__nuv,
 vlc_entry__ogg,
 vlc_entry__opus,
 vlc_entry__packetizer_avparser,
 vlc_entry__packetizer_copy,
 vlc_entry__packetizer_dirac,
 vlc_entry__packetizer_flac,
 vlc_entry__packetizer_h264,
 vlc_entry__packetizer_hevc,
 vlc_entry__packetizer_mlp,
 vlc_entry__packetizer_mpeg4audio,
 vlc_entry__packetizer_mpeg4video,
 vlc_entry__packetizer_mpegvideo,
 vlc_entry__packetizer_vc1,
 vlc_entry__param_eq,
 vlc_entry__playlist,
 vlc_entry__png,
 vlc_entry__ps,
 vlc_entry__pva,
 vlc_entry__quartztext,
 vlc_entry__rar,
 vlc_entry__rawaud,
 vlc_entry__rawdv,
 vlc_entry__rawvid,
 vlc_entry__rawvideo,
 vlc_entry__record,
 vlc_entry__rotate,
 vlc_entry__rtp,
 vlc_entry__rv32,
 vlc_entry__sap,
 vlc_entry__scale,
 vlc_entry__scaletempo,
 vlc_entry__scte27,
 vlc_entry__sdp,
 vlc_entry__securetransport,
 vlc_entry__sftp,
 vlc_entry__simple_channel_mixer,
 vlc_entry__smooth,
 vlc_entry__spatializer,
 vlc_entry__speex,
 vlc_entry__spudec,
 vlc_entry__stereo_widen,
 vlc_entry__stl,
 vlc_entry__subsdec,
 vlc_entry__subsdelay,
 vlc_entry__substx3g,
 vlc_entry__subsusf,
 vlc_entry__subtitle,
 vlc_entry__svcdsub,
 vlc_entry__swscale,
 vlc_entry__taglib,
 vlc_entry__tcp,
 vlc_entry__telx,
 vlc_entry__theora,
 vlc_entry__timecode,
 vlc_entry__transform,
 vlc_entry__trivial_channel_mixer,
 vlc_entry__ts,
 vlc_entry__tta,
 vlc_entry__ty,
 vlc_entry__udp,
 vlc_entry__ugly_resampler,
 vlc_entry__uleaddvaudio,
 vlc_entry__vc1,
 vlc_entry__vdr,
 vlc_entry__vmem,
 vlc_entry__vobsub,
 vlc_entry__voc,
 vlc_entry__vod_rtsp,
 vlc_entry__vorbis,
 vlc_entry__vout_ios2,
 vlc_entry__vpx,
 vlc_entry__wav,
 vlc_entry__xa,
 vlc_entry__xml,
 vlc_entry__yuv,
 vlc_entry__yuvp,
 vlc_entry__yuy2_i420,
 vlc_entry__yuy2_i422,
 vlc_entry__zip,
 vlc_entry__zvbi,
 NULL
};

